service: my-appsync-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  environment:
    PUBLIC_KEY_BASE64: ${file(./authorizer/publicKey.base64)}

package:
  individually: true
# AWS環境：AWSでデプロイして動作確認する場合コメントアウト
# ローカル環境：ローカル環境で動作確認する場合コメントアウト
functions: # AWS環境
  auth:
    handler: authorizer/handler.handler
    runtime: nodejs18.x
    package:
      patterns:
        - "!**"
        - "authorizer/**"
plugins:
  - serverless-dynamodb
  - serverless-appsync-simulator
  - serverless-appsync-plugin
  - serverless-offline

custom:
  appsync-simulator:
    port: 20002
    location: .
    apiKey: "0123456789"
    watch: true
    dynamoDb:
      accessKeyId: local
      secretAccessKey: local
  serverless-dynamodb:
    stages:
      - dev
    port: 8000
    docker: false
    start:
      migrate: true
      host: 127.0.0.1
  appSync:
    schema: graphql/schema.graphql
    name: confirm-payment-status-api
    authenticationType: AWS_LAMBDA # AWS環境
    # authenticationType: API_KEY # ローカル環境
    # apiKey: "0123456789" # ローカル環境
    lambdaAuthorizerConfig: # AWS環境
      authorizerResultTtlInSeconds: 300
      identityValidationExpression: ".*"
      functionName: auth
    mappingTemplatesLocation: resolvers
    mappingTemplates:
      - dataSource: PaymentStatusTable
        type: Mutation
        field: updatePaymentStatus
        request: updatePaymentStatus-request.vtl
        response: updatePaymentStatus-response.vtl
      - dataSource: PaymentStatusTable
        type: Subscription
        field: onPaymentStatusChanged
        request: onPaymentStatusChanged-request.vtl
        response: onPaymentStatusChanged-response.vtl
      - dataSource: PaymentStatusTable
        type: Query
        field: getPaymentStatus
        request: getPaymentStatus-request.vtl
        response: getPaymentStatus-response.vtl
    dataSources:
      - type: AMAZON_DYNAMODB
        name: PaymentStatusTable
        config:
          tableName: PaymentStatusTable
        endpoint: http://localhost:8000
        region: ap-northeast-1

resources:
  Resources:
    PaymentStatusTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PaymentStatusTable
        AttributeDefinitions:
          - AttributeName: reservation_id
            AttributeType: S
        KeySchema:
          - AttributeName: reservation_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
